### ISSUE TITLE
Support kubernetes log formats

### ISSUE THREAD

**Issue by blt** [DataDog/lading#10]
It would be valuable to be able to produce logs in the structured forms that kubernetes has: 

https://kubernetes.io/docs/concepts/cluster-administration/system-logs/

**Comment by spencergilbert** [comment]
I'll see if I can get this implemented, even though it might be "old" soon in the k8s world

**Comment by blt** [comment]
Oh? What's replacing it?

**Comment by spencergilbert** [comment]
"[structured](https://kubernetes.io/docs/concepts/cluster-administration/system-logs/#structured-logging)" and [json](https://kubernetes.io/docs/concepts/cluster-administration/system-logs/#json-log-format) were introduced as alpha in 1.19

**Comment by blt** [comment]
TIL
