### ISSUE TITLE
Allow HTTP `blackhole` to respond with additional payloads. 

### ISSUE THREAD

**Issue by blt** [DataDog/lading#101]
As of this writing `blackhole` has only a few response payloads:

* blank
* AWS Kinesis

It would be useful if the following responses were also available:

- [ ] Elasticsearch 
- [ ] S3
- [ ] Static byte sequence

Currently the body variants are here: https://github.com/blt/lading/blob/5acb3c419958536d43282ebfaa5c05042bd49b40/src/blackhole/http.rs#L32-L39

**Comment by GeorgeHahn** [comment]
We may consider wiring this up to the new `payload` module if the implementation is reasonable. That will allow any payload to be used as a blackhole response. That would give us access to the generic payloads and offer a framework to build out specialized response payloads.
