### ISSUE TITLE
Support metrics generation

### ISSUE THREAD

**Issue by spencergilbert** [DataDog/lading#153]
We should add the ability for `lading` to produce metric style events to unblock additional soak test configurations. Depending on the metrics and "flavor" of metrics this may be a new generator or a new variant of existing generators.

We'll likely want to create separate tickets for the metric formats and flavors we want to include in `lading`

**Comment by blt** [comment]
Seems straightforward to do as a payload, defined [here](https://github.com/blt/lading/tree/main/src/payload). Then we'd just need to expand the payloads supported by whatever generator. Possibly relates to #55.
