### ISSUE TITLE
Open question: should OpenTelemetry payloads have recent timestamps?

### ISSUE THREAD

**Issue by GeorgeHahn** [DataDog/lading#305]
OpenTelemetry consumers may drop payloads with distant timestamps. This could cause significant performance differences if some consumers drop payloads more aggressively than others.

This is a tradeoff. Timestamp generation should optimally be deterministic. That precludes the use of system time based bounds. The best we can do while maintaining determinism may be to bound timestamps to a far larger block of time, like the current decade.

**Comment by blt** [comment]
Oh, interesting. In any of the other payloads that have timestamps we do have fully deterministic times, but you're right that consumers may drop old timestamps and improve performance thereby. Hmm. Maybe we leave it fully deterministic for now and just document real well that we're going to be kicking out possibly ancient or far-future timestamps?

**Comment by GeorgeHahn** [comment]
I agree, I think that's the best option for now.

One other option is to add configs for timestamp generation. Generating times within a range would be powerful. That would add enough complexity that I prefer to wait until someone needs it though.
