### ISSUE TITLE
Add support for unicode tags in dogstatsd generation

### ISSUE THREAD

**Issue by scottopell** [DataDog/lading#668]
From https://docs.datadoghq.com/getting_started/tagging/#define-tags

> Tags can be up to 200 characters long and support Unicode letters (which includes most character sets, including languages such as Japanese).

**Comment by blt** [comment]
> which includes most character sets

The question that would need answering is which character sets are allowed. Otherwise I think it's a pretty achievable lift.

**Comment by scottopell** [comment]
I think this is just imprecise wording in the documentation, from what I understand unicode _is_ the character set.

From the Agent's perspective we support whatever golang does, which should be all of unicode, in either utf-8 or utf-16 encoding (again, what golang supports).

**Comment by scottopell** [comment]
never seen this in the wild, not worth keeping this open
